### ISSUE TITLE
Interact with d3 using D3Magic?

### ISSUE THREAD

**Issue by zahachtah** [JobJob/D3Magic.jl#1]
I just wonder if there is an easy way to make Julia code change values that the d3 figure then updates interactively, maybe even while running a loop, but otherwise just updating the d3 figure e.g. as a cell gets evaluated in the notebook ( I am no good at javascript and such, but I guess this has to do with weather a DOM element in one cell is accessible from another cell?). I guess now you can use Julia to calculate e.g. an array of values, insert it into a string of d3 code and display that with d3Magic.jl. but could you update this after its been displayed?

**Comment by JobJob** [comment]
So here's an example. It's not that pretty, or efficient, but it works - if you move the slider, one of the bars will move up and down. It uses the `@manipulate` macro from [Interact.jl](https://github.com/JuliaGizmos/Interact.jl). Note in the dataset the `$i` interpolated into the data array.
```
using Interact
@manipulate for i in 1:30
    d3code = """
        <g></g>

        <style>
        element {
            height: 25px;
        }
        div.bar {
            display: inline-block;
            width: 20px;
            height: 75px;
            margin-right: 2px;
            background-color: teal;
        }
        </style>

        <script>
        var dataset = [ 5, 10, 13, 19, 21, $i, 22, 18, 15, 13,
                        11, 12, 15, 20, 18, 17, 16, 18, 23, 25 ];

        d3.select("g").selectAll("div")
            .data(dataset)
            .enter()
            .append("div")
            .attr("class", "bar")
            .style("height", function(d) {
                var barHeight = d * 5;
                return barHeight + "px";
            });
        </script>
    """
    IJulia.clear_output()
    @d3_str d3code
end;
```

Anyway, at some point I will likely improve this, so we can leave this open for now.

**Comment by JobJob** [comment]
n.b. you'll need to update to the latest version.

**Comment by zahachtah** [comment]
Thanks!

**Comment by xiaohk** [comment]
Is it possible to implement tooltip using D3Magic? Like this [example ](http://bl.ocks.org/biovisualize/1016860). I am having some troubles to implement it, since it seems we cannot select `body` in the JS code.

**Comment by xiaohk** [comment]
It seems `IJulia.clear_output()` now also clears the slider. Any workaround?

**Comment by JobJob** [comment]
@xiaohk  I've added an example of how to use Interact/InteractNext in the README.

On the latest master (`Pkg.update()` should get you there), I've added `d3._select` and `d3._selectAll` that allow you to select things outside the "sandbox" that D3Magic creates. So you can select `<body>` with `d3._select("body")`. 

The example below should work, let me know how you go.
```
d3"""
<div class="example_div"></div>
<script>
var tooltip = d3._select("body")
    .append("div")
    .attr("class", "jjtooltip")
	.style("position", "absolute")
	.style("z-index", "10")
	.style("visibility", "hidden")
	.text("a simple tooltip");
	
var sampleSVG = d3.select(".example_div")
	.append("svg:svg")
	.attr("class", "sample")
	.attr("width", 300)
	.attr("height", 300);    
	
d3.select(".example_div svg")
	.append("svg:circle")
	.attr("stroke", "black")
	.attr("fill", "aliceblue")
	.attr("r", 50)
	.attr("cx", 52)
	.attr("cy", 52)
	.on("mouseover", function(){
        return tooltip.style("visibility", "visible");
    })
	.on("mousemove", function(){
        // debugger
        return tooltip.style("top", (event.y-10)+"px").style("left",(event.x+10)+"px");
    })
	.on("mouseout", function(){return tooltip.style("visibility", "hidden");});
</script>
"""
```
